### ISSUE TITLE
Unicode character ranges beyond \uFFFF in W3C parser

### ISSUE THREAD

**Issue by ptgolden** [menduz/node-ebnf#5]
I'm creating a parser for the [W3C standard for Turtle](https://dvcs.w3.org/hg/rdf/file/tip/rdf-turtle/turtle.bnf). The rule for PN_CHARS_BASE, on line 107, includes the range `[#10000-#EFFFF]`. The function in this library to convert regular expressions in W3C EBNF does not seem to allow representing code points above `\uFFFF`.

https://github.com/menduz/node-ebnf/blob/c7b61bccaa1badd9d1a6f8f4691349de65fb926c/src/Grammars/W3CEBNF.ts#L213-L220

It looks like the [highest code point in Unicode](http://unicode.org/L2/L2011/11072-regex2.html) is `\u10FFFF`, which is 6 characters. Would you accept a PR changing the regex in line 215 to match anywhere from four to six characters? (Theoretically, a six character range could be invalid, but it seems like too much of a hassle to do that sort of sanity check in this library).

**Comment by menduz** [comment]
Thanks! Yes, we accept PRs, go for it!

JS regular expressions only accept ranges between 0x0 and 0xFFFF, that's a hard limitation we have

**Comment by cuixiping** [comment]
JS regular expressions supports unicode flag.
```
/\u{1f602}/u.test('😂');
```

**Comment by menduz** [comment]
Pull requests are welcome
